### ISSUE TITLE
cache tikz not working in \robExtConfigure

### ISSUE THREAD

**Issue by dflvunoooooo** [leo-colisson/robust-externalize#14]
If I run code in a CacheMeCode environment and want to cache the generated tikz file as well, this is working perfektly with the `\cacheTikz` command. But if I set the option in the \robExtConfigure option, it is not applied. Here is my document:

```
\documentclass{scrreport}

\usepackage{robust-externalize}
\setPlaceholder*{__ROBEXT_LATEX_ENGINE__}{xelatex}  % Für das robustExternalize-Paket.
\runHereAndInPreambleOfCachedFiles{
    \usepackage{fontspec}
    \usepackage{gnuplot-lua-tikz}			
}
\robExtConfigure{
    tikz terminal/.append style={
        cache tikz,
    }
}

%\setmainfont{TeX Gyre Adventor}		

\begin{document}

This is a text to show the applied font.

\begin{figure}
    \begin{CacheMeCode}{gnuplot, tikz terminal={size 8cm,5cm}}
        set xlabel "Bla bla test test"
        plot cos(x)
    \end{CacheMeCode}
\end{figure}
	
\end{document}
```

If one does run this with the `setmainfont` commented out, the standard font is applied. If in the second step this option is activated and the file compiled again, the font will be applied to the figure too, as can be seen in the x label. If one does this step without the `\robExtConfigure` option and instead with the `\cacheTikz` option, The font change for the second compilation is not applied to the x label in the figure.

**Comment by tobiasBora** [comment]
Oh good catch, this is because I made a mistake in the documentation: `tikz terminal` is created/reset every time we call the `gnuplot` style, so we need to modify it inside the `gnuplot` preset, like:
```
\documentclass{scrreport}

\usepackage{robust-externalize}
\setPlaceholder*{__ROBEXT_LATEX_ENGINE__}{xelatex}  % Für das robustExternalize-Paket.
\runHereAndInPreambleOfCachedFiles{
    \usepackage{fontspec}
    \usepackage{gnuplot-lua-tikz}			
}
\robExtConfigure{
  add to preset={gnuplot}{
    tikz terminal/.append style={
      cache tikz,
    }
  }
}

\setmainfont{TeX Gyre Adventor}		

\begin{document}

This is a text to show the applied font.

\begin{figure}
    \begin{CacheMeCode}{gnuplot, tikz terminal={size 8cm,5cm}}
        set xlabel "Bla bla test test"
        plot cos(x)
    \end{CacheMeCode}
\end{figure}
	
\end{document}
```
The doc is not up to date.
