### ISSUE TITLE
gnuplot conversion adds tabs as ^^I

### ISSUE THREAD

**Issue by dflvunoooooo** [leo-colisson/robust-externalize#16]
If gnuplot code is run with the `CacheMeCode` environment, the tabs in the gnuplot code are converted to `^^I` in the gnuplot code tex file. If run without robust-externalize, those tabs are deleted and replaced with one space. Here is an example:

```
\documentclass{scrreport}

\usepackage{robust-externalize}
\setPlaceholder*{__ROBEXT_LATEX_ENGINE__}{xelatex}  % Für das robustExternalize-Paket.
\runHereAndInPreambleOfCachedFiles{
    \usepackage{gnuplottex}
    \usepackage{gnuplot-lua-tikz}			
}

\begin{document}

\begin{figure}
    \centering  
    \begin{CacheMeCode}{gnuplot, tikz}
       plot cos(x)				# This is a comment seperated with 4 tabs.    
    \end{CacheMeCode}
\end{figure}

\begin{figure}
    \begin{gnuplot}[terminal=tikz]
        plot cos(x)				# This is a comment seperated with 4 tabs.
    \end{gnuplot}
\end{figure}
	
\end{document}
```

Edit: Typo in code.

**Comment by tobiasBora** [comment]
Ahhh ok, so it seems to be a bug of `xelatex` (lualatex and pdflatex does not have this problem, you might want to use it meanwhile). I will try to investigate why…

**Comment by dflvunoooooo** [comment]
Oh, I didn't check that, sorry!

**Comment by tobiasBora** [comment]
Well, this is still a valid remark, thanks ^^

**Comment by tobiasBora** [comment]
I created a question [here](https://tex.stackexchange.com/questions/705247/xelatex-does-not-handle-tabs-correctly-when-writting-to-a-file), hopefully someone knows how to solve it.

**Comment by dflvunoooooo** [comment]
I am having a similar error with pdflatex. Compiled with pdflatex. In the robust-externalize log it says:
```
\boxRobExt=\box66

! You can't use `macro parameter character #' in restricted horizontal mode.
l.15          plot cos(x)^^I^^I^^I^^I#
                                       This is a comment seperated with 4 tabs.
```
And in the main log:
```
Source saved in robustExternalize/robExt-259F57E50F3F7B5B3CD606BF49601943.tex.
[robExt]We will start the compilationusing: cd robustExternalize/ && xelatex -h
alt-on-error "robExt-259F57E50F3F7B5B3CD606BF49601943.tex".
runsystem(cd robustExternalize/ && xelatex -halt-on-error "robExt-259F57E50F3F7
B5B3CD606BF49601943.tex")...executed.



! Package robExt Error: The pdf file
(robExt)               
robustExternalize/robExt-259F57E50F3F7B5B3CD606BF49601943.pdf
(robExt)                is not present. The compilation command "cd
(robExt)                robustExternalize/ && xelatex -halt-on-error
(robExt)                "robExt-259F57E50F3F7B5B3CD606BF49601943.tex"" used
(robExt)                to compile the environment on line 16 certainly
(robExt)                failed, see logs above or in
(robExt)               
robustExternalize/robExt-259F57E50F3F7B5B3CD606BF49601943.log.

Type <return> to continue.
 ...                                              
                                                  
l.16     \end{CacheMeCode}
                          

LaTeX does not know anything more about this error, sorry.
```

Compiled with xelatex. The robust-externalize log:
```
\writeRobExt=\write5
\openout5 = `robExt-04F1D9403B24AC2CEC9BAD0282ACE14E-out.tex'.

\boxRobExt=\box66

! You can't use `macro parameter character #' in restricted horizontal mode.
l.15          plot cos(x)^^I^^I^^I^^I#
                                       This is a comment seperated with 4 tabs.
```

The main log:
```
Source saved in robustExternalize/robExt-04F1D9403B24AC2CEC9BAD0282ACE14E.tex.
[robExt]We will start the compilationusing: cd robustExternalize/ && xelatex -h
alt-on-error "robExt-04F1D9403B24AC2CEC9BAD0282ACE14E.tex".
runsystem(cd robustExternalize/ && xelatex -halt-on-error "robExt-04F1D9403B24A
C2CEC9BAD0282ACE14E.tex")...executed.



! Package robExt Error: The pdf file
(robExt)               
robustExternalize/robExt-04F1D9403B24AC2CEC9BAD0282ACE14E.pdf
(robExt)                is not present. The compilation command "cd
(robExt)                robustExternalize/ && xelatex -halt-on-error
(robExt)                "robExt-04F1D9403B24AC2CEC9BAD0282ACE14E.tex"" used
(robExt)                to compile the environment on line 16 certainly
(robExt)                failed, see logs above or in
(robExt)               
robustExternalize/robExt-04F1D9403B24AC2CEC9BAD0282ACE14E.log.

Type <return> to continue.
 ...                                              
                                                  
l.16     \end{CacheMeCode}
                          

LaTeX does not know anything more about this error, sorry.
```

Looks almost identical.

**Comment by tobiasBora** [comment]
So wait, with xelatex I managed to get it work by compiling with the `-8bit` option: 
```
xelatex -8bit -shell-escape test
```

**Comment by dflvunoooooo** [comment]
Interesting. I can confirm. Your code with the `-8bit` option is working. The `--enable-8bit-chars` option still fails. As well as my code.

**Comment by dflvunoooooo** [comment]
Your code compiled with the `-8bit` option does even work, if `
\setPlaceholder*{__ROBEXT_LATEX_ENGINE__}{xelatex}  % Für das robustExternalize-Paket.` is added to your code.

**Comment by tobiasBora** [comment]
I’m a bit lost, first `tikz` should not be used with `gnuplot`, I think you meant `tikz terminal`. I also tried to compile your code with `xelatex -8bit foo.tex` and `pdflatex -8bit foo.tex` and both of them work. Here is the exact file I am using:
```
\documentclass{scrreport}

\usepackage{robust-externalize}
\setPlaceholder*{__ROBEXT_LATEX_ENGINE__}{xelatex}  % Für das robustExternalize-Paket.
\runHereAndInPreambleOfCachedFiles{
    \usepackage{gnuplottex}
    \usepackage{gnuplot-lua-tikz}			
}

\begin{document}

\begin{figure}
    \centering  
    \begin{CacheMeCode}{gnuplot, tikz terminal}
       plot cos(x)				# This is a comment seperated with 4 tabs.    
    \end{CacheMeCode}
\end{figure}

\begin{figure}
    \begin{gnuplot}[terminal=tikz]
        plot cos(x)				# This is a comment seperated with 4 tabs.
    \end{gnuplot}
\end{figure}
	
\end{document}
```
If it fails for you, can you copy/paste exactly the file you are using and the whole compilation command?

**Comment by dflvunoooooo** [comment]
I don't know what I did run. Your code works, with and without the `\runHereAndInPreambleOfCachedFiles{…}` command, sorry. So the `-8bit` option does the trick.

**Comment by tobiasBora** [comment]
Ok cool. If you find other edge cases where this fails, please reopen.

**Comment by tobiasBora** [comment]
Ok cool, I just added a section in the doc explaining this edge case as discussed in https://tex.stackexchange.com/questions/14771/tabs-in-output-file-written-by-xelatex-and-pdflatex-are-different. After googling for a bit, seems like it is the only solution (beside turning tabs into space in your editor directly :-P ).

**Comment by tobiasBora** [comment]
So beside the `-8bit` option, you can also follow [egreg's advice](https://tex.stackexchange.com/questions/705247/xelatex-does-not-handle-tabs-correctly-when-writting-to-a-file?noredirect=1#comment1753276_705247):

> The strategy is very simple: never use TAB when dealing with TeX. Reserve the TAB key to trigger autocompletion and your life will be happier. 

In TeXstudio, you can change this behavior via these two options:

```
Options > Configure TeXstudio > Editor > Replace indentation tabs with spaces
Options > Configure TeXstudio > Editor > Replace tabs in text with spaces
```

**Comment by dflvunoooooo** [comment]
> Ok cool, I just added a section in the doc explaining this edge case as discussed in https://tex.stackexchange.com/questions/14771/tabs-in-output-file-written-by-xelatex-and-pdflatex-are-different. After googling for a bit, seems like it is the only solution (beside turning tabs into space in your editor directly :-P ).

I will, thank you. Just to clarify, gnuplot itself doesn't care about indention, be they tabs or spaces. Only the conversion from tabs to ^^I is the problem.

**Comment by dflvunoooooo** [comment]
> So beside the `-8bit` option, you can also follow [egreg's advice](https://tex.stackexchange.com/questions/705247/xelatex-does-not-handle-tabs-correctly-when-writting-to-a-file?noredirect=1#comment1753276_705247):
> 
> > The strategy is very simple: never use TAB when dealing with TeX. Reserve the TAB key to trigger autocompletion and your life will be happier.
> 
> In TeXstudio, you can change this behavior via these two options:
> 
> ```
> Options > Configure TeXstudio > Editor > Replace indentation tabs with spaces
> Options > Configure TeXstudio > Editor > Replace tabs in text with spaces
> ```

Yes, that works, thank you :)

**Comment by tobiasBora** [comment]
> I will, thank you. Just to clarify, gnuplot itself doesn't care about indention, be they tabs or spaces. Only the conversion from tabs to ^^I is the problem.

Yeah, I also realized that, but I was initially confused because this bug is not present in pdflatex, so gnuplot was actually receiving spaces. I just fixed the doc.
