### ISSUE TITLE
Can not use resizebox around python cacheMeCode

### ISSUE THREAD

**Issue by dflvunoooooo** [leo-colisson/robust-externalize#24]
I somehow can not use a resizebox around a python preset. I get the error `You can't use `macro parameter character #' in math mode`.

```
\documentclass{scrartcl} 

\usepackage{robust-externalize}

\begin{document}
\begin{figure}
    \centering
    \resizebox{\textwidth}{!}{
    \begin{CacheMeCode}{python}
        import matplotlib.pyplot as plt
        import matplotlib
        matplotlib.use('pgf')
        year = [2014, 2015, 2016, 2017, 2018, 2019]
        tutorial_count = [39, 117, 111, 110, 67, 29]
        plt.plot(year, tutorial_count, color="#6c3376", linewidth=2)
        plt.title("Simple plot")
        plt.xlabel('Year')
        plt.ylabel('Number of futurestud.io Tutorials')
        print(get_filename_from_extension(".pgf"))
        plt.savefig("__ROBEXT_OUTPUT_PDF__")
    \end{CacheMeCode}
    }
    \caption{test}%
    \label{py:test}
\end{figure}

\end{document}
```

**Comment by dflvunoooooo** [comment]
Perfekt, thank you once again! 

> Note also a few remarks:
1. Yes, I read that in the docs, but in my editor tabs are replaced with spaces and it is working with python, tikz and gnuplot that way.  Interesting, that it is running none the less.

2. I yes, that is clear now. Thank you. There with the `matplotlib.use('pgf')` option, there is a pdf created containing only "ok".

**Comment by dflvunoooooo** [comment]
Perfekt, thank you once again! 

> Note also a few remarks:
1. Yes, I read that in the docs, but in my editor tabs are replaced with spaces and it is working with python, tikz and gnuplot that way.  Interesting, that it is running none the less.

2. I yes, that is clear now. Thank you. There with the `matplotlib.use('pgf')` option, there is a pdf created containing only "ok".

**Comment by tobiasBora** [comment]
1. For any language that do nwt care about indentation, it is not a problem, but python does care, it works only due to a very nasty coincidence and canhave weird side effects as you experienced. BUT in the very latest version, this is solved! **You can now freely indent your python code** (you can even use a fixed string in front of all lines in order to let your editor automatically indent the code without disturbing python, see the doc in additions to 2.6)
