### ISSUE TITLE
Nondescriptive error message & fix issue with pythonhighlight changing their style name

### ISSUE THREAD

**Issue by user202729** [leo-colisson/robust-externalize#33]
Source code:

```
\documentclass{article}
\usepackage{tcolorbox}
\usepackage{listings}
\usepackage{robust-externalize}
\begin{document}
\begin{CacheMeCode}{python print code and result}
print("Hello world")
\end{CacheMeCode}
\end{document}
```

Error message:

```
! Package Listings Error: Couldn't load requested style.
```

**Comment by user202729** [comment]
There is [conditionals - Test if a package (or package option) is loaded - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/16199/test-if-a-package-or-package-option-is-loaded) to check if a package is loaded.

**Comment by user202729** [comment]
That sounds reasonable.  https://tex.stackexchange.com/q/16199/250119 can be used to check if the package is loaded.

Speaking of which

```
\robExtSetPlaceholder{__ROBEXT_PYTHON_LSTINPUT_STYLE__}{frame=single, breakindent=.5\textwidth, frame=single, breaklines=true, style=mypython}
```

Seems `frame=single` is doubled for no reason?

**Comment by user202729** [comment]
For now, `pythonhighlight` package updated the internal `listings` style name to `pythonhighlight-style`, which hopefully would make the error message more understandable.

Next step might be to ask `listings` package to print the name on the first error message.

**Comment by tobiasBora** [comment]
Yeah, it is not so easy to do it properly without breaking backward compatibility of my package. What you describe might work, but uses `\AddToHook` that I try to avoid as it is only available since 2020 (quite recent in LaTeX life), that might still be in use by some editors.
