### ISSUE TITLE
\GetDocumentCommandArgSpec will be removed from kernel

### ISSUE THREAD

**Issue by mbertucci47** [leo-colisson/robust-externalize#6]
The commands `\(Get|Show)Document(Command|Environment)ArgSpec` and `\ArgumentSpecification` will be removed from the kernel in the next release, available only if xparse is explicitly loaded. Details in [this commit](https://github.com/latex3/latex2e/commit/0760f7ceb7d50ed8ee717f4f1f70484f28ff6e4e). The commands `\GetDocumentArgSpec` and `\ArgumentSpecification` are used in the definitions of `\robExtCacheCommand` and `\robExtArgumentList`.

**Comment by tobiasBora** [comment]
Oh thanks, good to know. That’s quite unfortunate (and I disagree that it is useful only for debugging, cf this package), but as I understand it should be enough to load `xparse` to get it back… Will correct soon.

**Comment by tobiasBora** [comment]
This should be fixed now, thanks for the report.
